/* LET ERP v37.6 - acabamento visual, progresso e dashboard personalizavel */
(()=>{
  const page=(location.pathname.split('/').pop()||'').toLowerCase();
  if(!page || ['login.html','index.html','tv_producao.html','tv_setor.html','tv_geral.html'].includes(page)) return;

  const STAGES=['Máquina','Lixação','Montagem','Colagem','Pintura','Fitagem','Embalagem'];
  const style=document.createElement('style');
  style.textContent=`
    :root{
      --erp-aqua:#2dd4cf;--erp-aqua-soft:#ecfeff;--erp-aqua-dark:#0f766e;
      --erp-navy:#083344;--erp-text:#0f172a;--erp-muted:#64748b;
      --erp-bg:#f5f7f9;--erp-card:#ffffff;--erp-line:#e2e8f0;
      --erp-shadow:0 5px 18px rgba(15,23,42,.055);
      --erp-radius:15px;
    }
    html{scroll-behavior:smooth}
    body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif!important;background:var(--erp-bg)!important;color:var(--erp-text)}
    button,input,select,textarea,a{font-family:inherit!important}
    h1,h2,h3,h4,strong,b{letter-spacing:-.01em}
    .stat,.column,.future-section,.date-filter-bar,.ready-item,.card,.panel,.modal-card,.overdue-section{border-color:var(--erp-line)!important;box-shadow:var(--erp-shadow)!important}
    .stats{gap:16px!important;padding-top:20px!important}.grid{gap:20px!important;padding-top:20px!important;padding-bottom:20px!important}
    .cards,.future-grid,.overdue-grid{gap:14px!important;padding:17px!important}.stat{padding:18px 20px!important;border-radius:var(--erp-radius)!important}.card{padding:16px!important;gap:16px!important;border-radius:var(--erp-radius)!important}
    .chip{background:#f1f5f9!important;color:#334155;border:1px solid #e8eef3}.market-chip{background:#ccfbf1!important;color:#115e59!important;border-color:#99f6e4!important}.observacoes{background:#f8fafc!important;border-color:#e8eef3!important}
    .input,.select,.textarea,input[type="text"],input[type="search"],input[type="date"],input[type="number"]{border-color:#cbd5e1!important}.input:focus,.select:focus,.textarea:focus,input:focus{outline:none!important;box-shadow:0 0 0 3px rgba(45,212,207,.15)!important;border-color:var(--erp-aqua)!important}
    .stat small,.deadline small,.field label,.order{letter-spacing:.38px!important}.stat b{font-weight:850!important;letter-spacing:-.04em}.client{font-weight:850!important;letter-spacing:-.025em}.head h2,.modal-head h3{font-weight:850!important;letter-spacing:-.025em}.card-btn,.btn,.new-btn,.stock-nav-btn,.date-filter-btn{font-weight:800!important;letter-spacing:.16px!important}
    .let-erp-drawer-icon,.let-erp-menu-group-btn .group-icon,.erp-ui-icon{display:inline-grid!important;place-items:center!important;border-radius:10px!important;background:#f1f5f9;color:var(--erp-navy);line-height:1!important}.let-erp-menu-group-btn .group-icon{width:27px;height:27px;font-size:13px!important;flex:0 0 27px}.erp-ui-icon{width:28px;height:28px;margin-right:7px;font-size:14px;vertical-align:middle}.stat small{display:flex;align-items:center}
    @keyframes erpFadeUp{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:translateY(0)}}@keyframes erpModalIn{from{opacity:.65;transform:translateY(8px) scale(.992)}to{opacity:1;transform:none}}
    .erp-enter{animation:erpFadeUp .28s ease both}.modal-card{animation:erpModalIn .2s ease both}.stat,.card,.ready-item,.let-erp-drawer-link,.card-btn,.btn,.new-btn,.date-filter-btn{transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease,background-color .16s ease!important}.stat:hover,.card:hover{transform:translateY(-2px);box-shadow:0 10px 26px rgba(15,23,42,.09)!important}.card-btn:hover,.btn:hover,.new-btn:hover,.date-filter-btn:hover{transform:translateY(-1px)}
    .erp-order-progress{margin-top:11px;max-width:520px}.erp-order-progress-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:5px;font-size:9px;font-weight:850;color:#475569}.erp-order-progress-head b{color:var(--erp-aqua-dark);font-size:9px}.erp-order-progress-track{height:8px;border-radius:999px;background:#e8eef3;overflow:hidden;box-shadow:inset 0 1px 2px rgba(15,23,42,.06)}.erp-order-progress-fill{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--erp-aqua),#14b8a6);transition:width .45s ease}.erp-order-progress-dots{display:grid;grid-template-columns:repeat(7,1fr);gap:3px;margin-top:5px}.erp-order-progress-dot{height:3px;border-radius:99px;background:#dbe3e8}.erp-order-progress-dot.done{background:#14b8a6}.erp-central-progress{margin:12px 0 0;padding:12px 14px;border:1px solid #d9efee;border-radius:12px;background:#f7fffe}
    .erp-dashboard-tools{max-width:1440px;margin:14px auto -4px;padding:0 28px;display:flex;justify-content:flex-end}.erp-customize-btn{height:34px;padding:0 12px;border:1px solid #cbd5e1;border-radius:10px;background:#fff;color:var(--erp-navy);font-size:9px;font-weight:850;cursor:pointer;display:inline-flex;align-items:center;gap:6px;box-shadow:0 3px 10px rgba(15,23,42,.04)}.erp-customize-btn:hover{border-color:#5eead4;background:#f0fdfa;transform:translateY(-1px)}.erp-pref-hidden{display:none!important}.stats.erp-personalized{grid-template-columns:repeat(auto-fit,minmax(190px,1fr))!important}main.grid.erp-personalized{grid-template-columns:repeat(auto-fit,minmax(360px,1fr))!important}
    .erp-custom-modal{position:fixed;inset:0;z-index:12050;background:rgba(15,23,42,.5);display:none;align-items:center;justify-content:center;padding:18px}.erp-custom-modal.open{display:flex}.erp-custom-card{width:min(620px,96vw);max-height:88vh;overflow:auto;background:#fff;border:1px solid var(--erp-line);border-radius:18px;box-shadow:0 28px 80px rgba(15,23,42,.28);animation:erpModalIn .2s ease}.erp-custom-head{padding:16px 18px;border-bottom:1px solid var(--erp-line);display:flex;align-items:center;justify-content:space-between;gap:12px}.erp-custom-head h3{margin:0;font-size:17px}.erp-custom-head p{margin:3px 0 0;font-size:10px;color:var(--erp-muted)}.erp-custom-close{width:34px;height:34px;border:0;border-radius:10px;background:#f1f5f9;color:#334155;font-size:18px;cursor:pointer}.erp-custom-body{padding:17px 18px}.erp-custom-title{font-size:9px;font-weight:900;color:#64748b;letter-spacing:.55px;margin-bottom:8px}.erp-widget-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.erp-widget-option{display:flex;align-items:center;gap:9px;border:1px solid #e2e8f0;border-radius:11px;padding:10px 11px;background:#fff;font-size:10px;font-weight:800;cursor:pointer}.erp-widget-option:hover{background:#f8fafc}.erp-widget-option input{width:17px;height:17px;accent-color:#14b8a6}.erp-order-list{display:grid;gap:6px;margin-top:8px}.erp-order-row{display:grid;grid-template-columns:1fr 32px 32px;gap:5px;align-items:center;border:1px solid #e2e8f0;border-radius:10px;padding:7px 8px;background:#f8fafc;font-size:10px;font-weight:800}.erp-order-row button{width:30px;height:28px;border:1px solid #dbe4ea;background:#fff;border-radius:8px;cursor:pointer;color:#334155}.erp-custom-foot{padding:13px 18px;border-top:1px solid var(--erp-line);display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap}.erp-pref-btn{height:36px;border:0;border-radius:10px;padding:0 13px;font-size:9px;font-weight:900;cursor:pointer}.erp-pref-btn.gray{background:#f1f5f9;color:#334155}.erp-pref-btn.primary{background:var(--erp-navy);color:#fff}
    @media(max-width:700px){.stats{gap:10px!important}.grid{gap:12px!important}.cards,.future-grid,.overdue-grid{padding:12px!important;gap:10px!important}.erp-dashboard-tools{padding:0 15px}.erp-widget-grid{grid-template-columns:1fr}main.grid.erp-personalized{grid-template-columns:1fr!important}}
    @media(prefers-reduced-motion:reduce){*{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}
  `;
  document.head.appendChild(style);

  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  async function getDb(){for(let i=0;i<60&&!window.letErpSupabase;i++)await sleep(100);return window.letErpSupabase||null}
  function decorateIcons(){const icons={todayStat:'📅',tomorrowStat:'🗓️',productionStat:'⚙️',readyStat:'✅'};Object.entries(icons).forEach(([id,ic])=>{const small=document.querySelector('#'+id+' small');if(small&&!small.querySelector('.erp-ui-icon'))small.insertAdjacentHTML('afterbegin','<span class="erp-ui-icon">'+ic+'</span>')})}
  function animateFresh(){document.querySelectorAll('.card:not([data-erp-animated]),.ready-item:not([data-erp-animated]),.stat:not([data-erp-animated])').forEach((el,i)=>{el.dataset.erpAnimated='1';el.classList.add('erp-enter');el.style.animationDelay=Math.min(i*22,140)+'ms';setTimeout(()=>{el.classList.remove('erp-enter');el.style.animationDelay=''},450)})}
  function orderMap(){try{if(typeof window.loadOrders==='function')return new Map(window.loadOrders().map(p=>[String(p.id),p]))}catch(e){}return new Map()}
  function parseOrderId(card){const t=card.querySelector('.order')?.textContent||'';const m=t.match(/PEDIDO\s*#([^\s]+)/i);return m?m[1]:null}
  function progressHtml(stageIndex,finished=false,extraClass=''){let idx=Math.max(0,Math.min(6,Number(stageIndex)||0));const pct=finished?100:Math.round(((idx+1)/7)*100),label=finished?'FINALIZADO':STAGES[idx],dots=STAGES.map((_,i)=>'<span class="erp-order-progress-dot '+((finished||i<=idx)?'done':'')+'"></span>').join('');return '<div class="erp-order-progress '+extraClass+'"><div class="erp-order-progress-head"><span>PROGRESSO DA PRODUÇÃO</span><b>'+esc(label)+' • '+pct+'%</b></div><div class="erp-order-progress-track"><div class="erp-order-progress-fill" style="width:'+pct+'%"></div></div><div class="erp-order-progress-dots">'+dots+'</div></div>'}
  function addCardProgress(){if(page!=='painel_producao.html')return;const map=orderMap();document.querySelectorAll('.card').forEach(card=>{const id=parseOrderId(card),p=id?map.get(String(id)):null;if(!p)return;const idx=Number(p.etapaAtual??p.etapa_atual??0),finished=!!p.finalizado||p.status==='Pronto';let box=card.querySelector('.erp-order-progress');const middle=card.children[1];if(!middle)return;if(!box){const meta=middle.querySelector('.meta');(meta||middle).insertAdjacentHTML(meta?'afterend':'beforeend',progressHtml(idx,finished))}else{const pct=finished?100:Math.round(((Math.max(0,Math.min(6,idx))+1)/7)*100),label=finished?'FINALIZADO':STAGES[Math.max(0,Math.min(6,idx))];box.querySelector('.erp-order-progress-fill')?.style.setProperty('width',pct+'%');const b=box.querySelector('.erp-order-progress-head b');if(b)b.textContent=label+' • '+pct+'%'}})}
  async function centralProgress(){if(page!=='pedido.html'||document.querySelector('.erp-central-progress'))return;const id=new URLSearchParams(location.search).get('id');if(!id)return;const db=await getDb();if(!db)return;try{const {data}=await db.from('pedidos').select('etapa_atual,finalizado,status').eq('id',id).maybeSingle();if(!data)return;const hero=document.getElementById('hero');if(!hero)return;const box=document.createElement('div');box.className='erp-central-progress';box.innerHTML=progressHtml(data.etapa_atual,!!data.finalizado||data.status==='Pronto');hero.insertAdjacentElement('afterend',box)}catch(e){console.warn('Progresso do pedido:',e)}}

  const WIDGETS=[['todayStat','📅 Pedidos de Hoje'],['tomorrowStat','🗓️ Pedidos de Amanhã'],['productionStat','⚙️ Pedidos em Produção'],['readyStat','✅ Pedidos Prontos'],['calendar','📆 Calendário de Envios'],['overdue','🚨 Atrasos Pendentes'],['todayColumn','🔴 Fila de Hoje'],['tomorrowColumn','🟠 Fila de Amanhã'],['future','🔵 Próximos Pedidos']];
  const STAT_IDS=['todayStat','tomorrowStat','productionStat','readyStat'];let prefs={visible:{},statOrder:[...STAT_IDS]},profileId=null;
  function defaultPrefs(){return{visible:Object.fromEntries(WIDGETS.map(([k])=>[k,true])),statOrder:[...STAT_IDS]}}
  function normalizePrefs(raw){const d=defaultPrefs(),r=raw&&typeof raw==='object'?raw:{};return{visible:{...d.visible,...(r.visible||{})},statOrder:Array.isArray(r.statOrder)?[...r.statOrder.filter(x=>STAT_IDS.includes(x)),...STAT_IDS.filter(x=>!r.statOrder.includes(x))]:d.statOrder}}
  function targetFor(k){if(STAT_IDS.includes(k))return document.getElementById(k);if(k==='calendar')return document.querySelector('.date-filter-wrap');if(k==='overdue')return document.getElementById('overdueWrap');if(k==='todayColumn')return document.getElementById('todayColumn');if(k==='tomorrowColumn')return document.getElementById('tomorrowColumn');if(k==='future')return document.querySelector('.future-wrap');return null}
  function applyPrefs(){if(page!=='painel_producao.html')return;WIDGETS.forEach(([k])=>targetFor(k)?.classList.toggle('erp-pref-hidden',prefs.visible[k]===false));const stats=document.querySelector('.stats');if(stats){prefs.statOrder.forEach(id=>{const el=document.getElementById(id);if(el)stats.appendChild(el)});stats.classList.add('erp-personalized');stats.classList.toggle('erp-pref-hidden',!STAT_IDS.some(id=>prefs.visible[id]!==false))}const grid=document.querySelector('main.grid');if(grid){grid.classList.add('erp-personalized');grid.classList.toggle('erp-pref-hidden',prefs.visible.todayColumn===false&&prefs.visible.tomorrowColumn===false)}}
  async function loadPrefs(){prefs=defaultPrefs();const db=await getDb();if(!db){try{prefs=normalizePrefs(JSON.parse(localStorage.getItem('letErpDashboardPrefs')||'{}'))}catch(e){};return applyPrefs()}try{const {data:s}=await db.auth.getSession();profileId=s?.session?.user?.id||null;if(profileId){const {data}=await db.from('perfis').select('dashboard_preferencias').eq('id',profileId).maybeSingle();prefs=normalizePrefs(data?.dashboard_preferencias)}}catch(e){console.warn('Preferências do dashboard:',e)}applyPrefs()}
  async function savePrefs(){applyPrefs();try{localStorage.setItem('letErpDashboardPrefs',JSON.stringify(prefs))}catch(e){}const db=await getDb();if(db&&profileId)try{await db.from('perfis').update({dashboard_preferencias:prefs}).eq('id',profileId)}catch(e){console.warn('Salvar dashboard:',e)}}
  function modalMarkup(){const options=WIDGETS.map(([k,l])=>'<label class="erp-widget-option"><input type="checkbox" data-widget="'+k+'"> <span>'+l+'</span></label>').join('');return '<div class="erp-custom-modal" id="erpDashboardModal"><div class="erp-custom-card"><div class="erp-custom-head"><div><h3>🧩 Personalizar Dashboard</h3><p>Escolha o que quer ver no Painel de Produção.</p></div><button class="erp-custom-close" type="button">×</button></div><div class="erp-custom-body"><div class="erp-custom-title">BLOCOS VISÍVEIS</div><div class="erp-widget-grid">'+options+'</div><div class="erp-custom-title" style="margin-top:17px">ORDEM DOS CARDS PRINCIPAIS</div><div class="erp-order-list" id="erpStatOrder"></div></div><div class="erp-custom-foot"><button class="erp-pref-btn gray" id="erpResetPrefs" type="button">RESTAURAR PADRÃO</button><button class="erp-pref-btn primary" id="erpSavePrefs" type="button">SALVAR PAINEL</button></div></div></div>'}
  function renderOrderRows(){const box=document.getElementById('erpStatOrder');if(!box)return;const labels=Object.fromEntries(WIDGETS);box.innerHTML=prefs.statOrder.map((id,i)=>'<div class="erp-order-row"><span>'+labels[id]+'</span><button type="button" data-up="'+i+'" '+(i===0?'disabled':'')+'>↑</button><button type="button" data-down="'+i+'" '+(i===prefs.statOrder.length-1?'disabled':'')+'>↓</button></div>').join('')}
  function syncModal(){document.querySelectorAll('[data-widget]').forEach(i=>i.checked=prefs.visible[i.dataset.widget]!==false);renderOrderRows()}
  async function dashboardCustomizer(){if(page!=='painel_producao.html')return;await loadPrefs();const stats=document.querySelector('.stats');if(!stats)return;const tools=document.createElement('div');tools.className='erp-dashboard-tools';tools.innerHTML='<button class="erp-customize-btn" type="button">⚙️ PERSONALIZAR PAINEL</button>';stats.before(tools);document.body.insertAdjacentHTML('beforeend',modalMarkup());const modal=document.getElementById('erpDashboardModal');tools.querySelector('button').onclick=()=>{syncModal();modal.classList.add('open')};modal.querySelector('.erp-custom-close').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal.addEventListener('change',e=>{if(e.target.matches('[data-widget]'))prefs.visible[e.target.dataset.widget]=e.target.checked});modal.addEventListener('click',e=>{const up=e.target.closest('[data-up]'),down=e.target.closest('[data-down]'),b=up||down;if(!b)return;const i=Number(b.dataset.up??b.dataset.down),j=up?i-1:i+1;if(j<0||j>=prefs.statOrder.length)return;[prefs.statOrder[i],prefs.statOrder[j]]=[prefs.statOrder[j],prefs.statOrder[i]];renderOrderRows()});document.getElementById('erpResetPrefs').onclick=()=>{prefs=defaultPrefs();syncModal()};document.getElementById('erpSavePrefs').onclick=async()=>{await savePrefs();modal.classList.remove('open')}}
  function refresh(){decorateIcons();animateFresh();addCardProgress()}
  const start=()=>{refresh();centralProgress();dashboardCustomizer();new MutationObserver(()=>refresh()).observe(document.body,{childList:true,subtree:true})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
