/* LET_ERP_V38_NAVIGATION_UX */
(()=>{
 const page=(location.pathname.split('/').pop()||'').toLowerCase();
 if(!page||['login.html','index.html','tv_producao.html','tv_setor.html','tv_geral.html'].includes(page))return;
 const groups=[
  ['🏭','PRODUÇÃO',['painel_producao.html','novo_pedido.html','setores.html','kanban.html','reenvios.html','calendario_envios.html']],
  ['📊','GESTÃO',['analises.html','atrasos.html','financeiro.html','programacoes.html']],
  ['📦','ESTOQUE',['estoque.html']],['🚚','EXPEDIÇÃO',['expedicao.html']],
  ['🔐','ADMINISTRAÇÃO',['atividades.html','permissoes.html','acessos.html','limpeza_historicos.html']],['👤','PERFIL',['perfil.html']]
 ];
 const labels={painel_producao:'Painel de Produção',novo_pedido:'Novo Pedido',setores:'Setores',kanban:'Kanban de Produção',reenvios:'Reenvios',calendario_envios:'Calendário de Envios',analises:'Análises',atrasos:'Pedidos Atrasados',financeiro:'Financeiro',programacoes:'Programações',estoque:'Estoque',expedicao:'Expedição',atividades:'Atividades',permissoes:'Permissões',acessos:'Gerenciar Acessos',limpeza_historicos:'Limpeza de Históricos',perfil:'Meu Perfil',pedido:'Central do Pedido'};
 const style=document.createElement('style');style.textContent=`
 body>.topbar{min-height:62px!important;padding-top:9px!important;padding-bottom:9px!important} body>.topbar h1{font-size:clamp(17px,1.7vw,23px)!important;margin-bottom:2px!important} body>.topbar p{font-size:9px!important}.let-erp-home-clover{top:9px!important}.let-erp-menu-button{top:10px!important}
 .v38-search{position:absolute;left:50%;top:10px;transform:translateX(-50%);z-index:70;width:min(390px,34vw);height:40px;background:#fff;border:1px solid #d8e4e8;border-radius:12px;display:flex;align-items:center;box-shadow:0 3px 12px #08334418}.v38-search span{width:40px;text-align:center}.v38-search input{flex:1;min-width:0;border:0;outline:0;background:transparent;font:800 11px Arial;color:#0f172a;padding-right:10px}.v38-results{display:none;position:fixed;z-index:10050;width:min(500px,calc(100vw - 24px));max-height:65vh;overflow:auto;background:#fff;border:1px solid #dbe4ea;border-radius:14px;box-shadow:0 22px 60px #0f172a33;padding:6px}.v38-results.open{display:block}.v38-rhead{font:950 8px Arial;color:#94a3b8;letter-spacing:.6px;padding:8px 9px 4px}.v38-result{display:grid;grid-template-columns:34px 1fr auto;gap:8px;align-items:center;padding:8px;border-radius:9px;color:#0f172a;text-decoration:none;font-family:Arial}.v38-result:hover{background:#ecfeff}.v38-result i{width:34px;height:34px;border-radius:8px;background:#f1f5f9;display:grid;place-items:center;font-style:normal}.v38-result strong{display:block;font-size:10px}.v38-result small{display:block;font-size:8px;color:#64748b;margin-top:2px}.v38-result b{font-size:7px;color:#0f766e;background:#ccfbf1;padding:4px 6px;border-radius:99px}.v38-empty{padding:22px;text-align:center;font:800 10px Arial;color:#64748b}
 .v38-crumbwrap{max-width:1440px;margin:9px auto 0;padding:0 18px;display:flex;align-items:center;gap:8px}.v38-back{height:30px;border:1px solid #dbe4ea;border-radius:9px;background:#fff;color:#083344;font:950 9px Arial;padding:0 10px;cursor:pointer}.v38-back:hover{background:#ecfeff}.v38-crumb{display:flex;gap:6px;align-items:center;flex-wrap:wrap;font:800 9px Arial;color:#64748b}.v38-crumb a{color:#0f766e;text-decoration:none;font-weight:950}.v38-crumb .cur{color:#334155;font-weight:950}
 .let-erp-drawer-body.v38{padding:8px 10px}.v38-group{border:1px solid #edf2f7;border-radius:12px;margin-bottom:7px;overflow:hidden}.v38-gbtn{width:100%;height:35px;border:0;background:#f8fafc;color:#334155;display:flex;align-items:center;gap:8px;padding:0 9px;font:950 9px Arial;cursor:pointer;text-align:left}.v38-gbtn .name{flex:1}.v38-group.closed .v38-links{display:none}.v38-links{padding:5px}.v38-links .let-erp-drawer-link{grid-template-columns:36px 1fr 24px 14px!important;padding:8px!important;margin-bottom:2px!important}.v38-links .let-erp-drawer-icon{width:34px!important;height:34px!important;font-size:15px!important}.v38-star{width:23px;height:23px;display:grid;place-items:center;border-radius:7px;color:#cbd5e1;cursor:pointer;font-size:14px}.v38-star.on{color:#f59e0b}.v38-star:hover{background:#fffbeb;color:#f59e0b}.v38-favs{border:1px solid #fde68a;background:#fffdf5;border-radius:12px;padding:5px;margin-bottom:8px}.v38-favs:empty{display:none}.v38-ftitle{padding:5px 7px;font:950 9px Arial;color:#92400e}
 @media(max-width:820px){.v38-search{left:auto;right:62px;transform:none;width:min(210px,42vw)}.v38-search input{font-size:9px}.v38-crumbwrap{padding:0 10px}.v38-back{padding:0 8px}}
 @media(max-width:560px){.v38-search{width:115px}.v38-search input::placeholder{color:transparent}.v38-crumb{font-size:8px;white-space:nowrap;flex-wrap:nowrap;overflow:auto}.v38-back{font-size:0}.v38-back:first-letter{font-size:11px}}
 `;document.head.appendChild(style);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const hrefName=h=>String(h||'').split('?')[0].split('/').pop().toLowerCase();
 const sleep=m=>new Promise(r=>setTimeout(r,m));
 async function db(){for(let i=0;i<60&&!window.letErpSupabase;i++)await sleep(100);return window.letErpSupabase}
 async function uid(){try{return (await (await db()).auth.getSession()).data?.session?.user?.id||null}catch(e){return null}}
 function filterKey(){return'v38filters:'+location.pathname} function saveFilters(){try{const o={};document.querySelectorAll('input[id],select[id]').forEach(x=>{const id=x.id.toLowerCase();if(/filter|filtro|search|busca|period|status/.test(id)&&x.type!=='password'&&x.type!=='file')o[x.id]=x.value});sessionStorage.setItem(filterKey(),JSON.stringify(o))}catch(e){}} function restoreFilters(){try{const o=JSON.parse(sessionStorage.getItem(filterKey())||'{}');Object.entries(o).forEach(([id,v])=>{const x=document.getElementById(id);if(x){x.value=v;x.dispatchEvent(new Event('input',{bubbles:true}));x.dispatchEvent(new Event('change',{bubbles:true}))}})}catch(e){}}
 function crumbs(){const top=document.querySelector('body>.topbar');if(!top||document.querySelector('.v38-crumbwrap'))return;const k=page.replace('.html',''),id=new URLSearchParams(location.search).get('id')||new URLSearchParams(location.search).get('pedido');let html=page==='painel_producao.html'?'<span class="cur">Painel</span>':'<a href="painel_producao.html">Painel</a><span>›</span>';if(page==='pedido.html'&&id)html+='<span class="cur">Pedido #'+esc(id)+'</span><span>›</span>';html+='<span class="cur">'+esc(labels[k]||document.title)+'</span>';const w=document.createElement('div');w.className='v38-crumbwrap';w.innerHTML='<button class="v38-back" type="button">↩️ VOLTAR</button><div class="v38-crumb">'+html+'</div>';top.after(w);w.querySelector('button').onclick=()=>{saveFilters();try{if(document.referrer&&new URL(document.referrer).origin===location.origin&&history.length>1){history.back();return}}catch(e){}location.href=sessionStorage.getItem('v38prev')||'painel_producao.html'};document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a||a.target==='_blank')return;try{const u=new URL(a.href,location.href);if(u.origin===location.origin){saveFilters();sessionStorage.setItem('v38prev',location.href)}}catch(x){}},true)}
 let favs=[],me=null;
 async function loadFav(){me=await uid();if(!me)return;try{const r=await (await db()).from('perfis').select('menu_favoritos').eq('id',me).maybeSingle();favs=Array.isArray(r.data?.menu_favoritos)?r.data.menu_favoritos.map(hrefName):[]}catch(e){favs=[]}}
 async function saveFav(){if(me)try{await (await db()).from('perfis').update({menu_favoritos:favs}).eq('id',me)}catch(e){}}
 function star(a){if(a.querySelector('.v38-star'))return;const h=hrefName(a.getAttribute('href')),sp=document.createElement('span');sp.className='v38-star'+(favs.includes(h)?' on':'');sp.textContent='★';sp.title=favs.includes(h)?'Remover dos favoritos':'Adicionar aos favoritos';sp.onclick=async e=>{e.preventDefault();e.stopPropagation();favs=favs.includes(h)?favs.filter(x=>x!==h):[...new Set([...favs,h])];await saveFav();document.querySelectorAll('.v38-star').forEach(s=>{const l=s.closest('a');if(l&&hrefName(l.getAttribute('href'))===h)s.classList.toggle('on',favs.includes(h))});renderFav()};const ar=a.querySelector('.let-erp-drawer-arrow');ar?a.insertBefore(sp,ar):a.appendChild(sp)}
 function renderFav(){const box=document.querySelector('.v38-favs');if(!box)return;const originals=[...document.querySelectorAll('.v38-links .let-erp-drawer-link')].filter(a=>favs.includes(hrefName(a.href))&&a.style.display!=='none');box.innerHTML=originals.length?'<div class="v38-ftitle">⭐ FAVORITOS</div>':'';originals.forEach(a=>{const c=a.cloneNode(true);c.querySelector('.v38-star')?.remove();c.onclick=()=>window.letErpCloseMenu?.();box.appendChild(c)})}
 async function menu(){let body;for(let i=0;i<50&&!body;i++){body=document.querySelector('.let-erp-drawer-body');if(!body)await sleep(80)}if(!body||body.classList.contains('v38'))return;await loadFav();const links=[...body.querySelectorAll('.let-erp-drawer-link')],map=new Map(links.map(a=>[hrefName(a.href),a]));body.innerHTML='';body.classList.add('v38');const f=document.createElement('div');f.className='v38-favs';body.appendChild(f);groups.forEach(([ic,n,hs])=>{const arr=hs.map(h=>map.get(h)).filter(Boolean);if(!arr.length)return;const s=document.createElement('section');s.className='v38-group';s.innerHTML='<button class="v38-gbtn" type="button"><span>'+ic+'</span><span class="name">'+n+'</span><span>⌄</span></button><div class="v38-links"></div>';arr.forEach(a=>{star(a);s.lastElementChild.appendChild(a)});s.firstElementChild.onclick=()=>s.classList.toggle('closed');body.appendChild(s)});const used=new Set(groups.flatMap(g=>g[2]));const extra=[...map].filter(([h])=>!used.has(h)).map(x=>x[1]);if(extra.length){const s=document.createElement('section');s.className='v38-group';s.innerHTML='<button class="v38-gbtn"><span>🧩</span><span class="name">OUTROS</span><span>⌄</span></button><div class="v38-links"></div>';extra.forEach(a=>{star(a);s.lastElementChild.appendChild(a)});body.appendChild(s)}renderFav()}
 let rbox;
 function posSearch(w){if(!rbox)return;const r=w.getBoundingClientRect();rbox.style.left=Math.max(12,Math.min(innerWidth-rbox.offsetWidth-12,r.left))+'px';rbox.style.top=(r.bottom+6)+'px'}
 function result(ic,t,sub,tag,href){return '<a class="v38-result" href="'+href+'"><i>'+ic+'</i><span><strong>'+esc(t)+'</strong><small>'+esc(sub)+'</small></span><b>'+tag+'</b></a>'}
 async function search(q,w){q=q.trim();if(q.length<2){rbox.innerHTML='<div class="v38-empty">Digite pelo menos 2 caracteres.</div>';rbox.classList.add('open');posSearch(w);return}const safe=q.replace(/[,%()]/g,' ').trim(),ql=q.toLowerCase();let p=[],pe=[],au=[];const mods=[...document.querySelectorAll('.v38-links .let-erp-drawer-link')].filter(a=>a.style.display!=='none'&&a.textContent.toLowerCase().includes(ql)).slice(0,5);try{const D=await db();p=(await D.from('pedidos').select('id,cliente,status,marketplace').or('id.ilike.%'+safe+'%,cliente.ilike.%'+safe+'%').limit(7)).data||[];pe=(await D.from('perfis').select('id,nome,setor,email').or('nome.ilike.%'+safe+'%,email.ilike.%'+safe+'%,setor.ilike.%'+safe+'%').limit(5)).data||[];if(q.length>2)au=(await D.from('auditoria').select('acao,tabela,registro_id,criado_em').or('registro_id.ilike.%'+safe+'%,tabela.ilike.%'+safe+'%,acao.ilike.%'+safe+'%').order('criado_em',{ascending:false}).limit(4)).data||[]}catch(e){}let h='';if(p.length)h+='<div class="v38-rhead">PEDIDOS</div>'+p.map(x=>result('📦','#'+x.id,(x.cliente||'')+' • '+(x.marketplace||'')+' • '+(x.status||''),'PEDIDO','pedido.html?id='+encodeURIComponent(x.id))).join('');if(mods.length)h+='<div class="v38-rhead">MÓDULOS</div>'+mods.map(a=>result(a.querySelector('.let-erp-drawer-icon')?.textContent||'🧩',a.querySelector('strong')?.textContent||a.textContent,a.querySelector('small')?.textContent||'','MÓDULO',a.getAttribute('href'))).join('');if(pe.length)h+='<div class="v38-rhead">FUNCIONÁRIOS</div>'+pe.map(x=>result('👤',x.nome||x.email,(x.setor||'')+' • '+(x.email||''),'PESSOA','atividades.html')).join('');if(au.length)h+='<div class="v38-rhead">HISTÓRICO</div>'+au.map(x=>result('🧾',(x.acao||'')+' • '+(x.tabela||''),'Registro '+(x.registro_id||'-'),'HIST.','atividades.html')).join('');rbox.innerHTML=h||'<div class="v38-empty">Nenhum resultado encontrado.</div>';rbox.classList.add('open');posSearch(w)}
 function globalSearch(){const top=document.querySelector('body>.topbar');if(!top||document.querySelector('.v38-search'))return;const w=document.createElement('div');w.className='v38-search';w.innerHTML='<span>🔎</span><input type="search" placeholder="Buscar no LET ERP...">';top.appendChild(w);rbox=document.createElement('div');rbox.className='v38-results';document.body.appendChild(rbox);let t;const i=w.querySelector('input');i.oninput=()=>{clearTimeout(t);t=setTimeout(()=>search(i.value,w),220)};i.onfocus=()=>search(i.value,w);i.onkeydown=e=>{if(e.key==='Escape'){rbox.classList.remove('open');i.blur()}};document.addEventListener('click',e=>{if(!w.contains(e.target)&&!rbox.contains(e.target))rbox.classList.remove('open')});window.addEventListener('resize',()=>posSearch(w))}
 async function init(){crumbs();globalSearch();restoreFilters();setTimeout(restoreFilters,600);await menu()}
 document.addEventListener('change',saveFilters);document.addEventListener('input',e=>{if(/filter|filtro|search|busca|period|status/i.test(e.target.id||''))saveFilters()});
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80)):setTimeout(init,80);
})();
